// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.DTOs
{
    public partial class DtoShipper
    {
        public DtoShipper()
        {
            Orders = new HashSet<DtoOrder>();
        }

        public int ShipperId { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<DtoOrder> Orders { get; set; }
    }
}